title: Nicole Kristen Uy # your name (or website title) here
logo: "/images/roundProfilePic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Programming has always been special to me. It's the ability to make something out of just strings of letters and numbers. The things people can make in this profession is practically limitless. For me, being able to do this is absolutely amazing.

  I recently graduated from Western Governors University with a BS in Software Development and am eager to use a develop my skills. 

  As hobbies I like developing my mobile game called "Tiny Planet Defender", creating projects to learn new programming languages, and also learning Spanish and Chinese.
  <br><br>
  I have experience in the following programming languages:
        
       •   C#
       •   Java
       •   C++
       •   JavaScript
       •   SQL
       •   HTML
       •   CSS3
       •   PHP
       •   JQuery 
  <br><br>
  <a href="https://www.linkedin.com/in/nicole-kristen-uy">View My LinkedIn Profile</a> 
  <br><br>
  <b>Projects:</b>
  <br><br>
  1. <a href="/50sPage">50's Diner Themed Website</a>
  <br>
  2. <a href="/GamePage">Tiny Planet Defender</a>
  <br>
  3. <a href="/SchoolManagerPage">School Manager Android Application</a>
  <br>
  4. <a href="/InventoryManagerPage">Inventory Manager Java Application</a>
  <br>
  5. <a href="/AppointmentManagerPage">Appointment Manager Java Application</a>

theme: jekyll-theme-minimal
