title: Nicole Kristen Uy # your name (or website title) here
logo: "/images/roundProfilePic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Friendly and Intuitive Software Developer who learns quickly and specializes in application, web, and game development.
  <br><br>
  <a href="https://www.linkedin.com/in/nicole-kristen-uy">View My LinkedIn Profile</a> 
  <br><br>
  <b>Projects:</b>
  <br><br>
  1. <a href="/50sPage">50's Diner Themed Website</a>
  <br>
  2. <a href="/GamePage">Tiny Planet Defender</a>
  <br>
  3. <a href="/SchoolManagerPage">School Manager Android Application</a>
  <br>
  4. <a href="/InventoryManagerPage">Inventory Manager Java Application</a>
  <br>
  5. <a href="/AppointmentManagerPage">Appointment Manager Java Application</a>
  <br><br>
  I have experience in the following programming languages:
        
       •   C#
       •   Java
       •   C++
       •   JavaScript
       •   SQL
       •   HTML
       •   CSS3
       •   PHP
       •   JQuery 
  
theme: jekyll-theme-minimal
